export type Question = {
  id: string;
  text: string;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  difficulty: "easy" | "medium" | "hard";
};

export type ExplanationText = {
  id: string;
  title: string;
  content: string;
  questions: Question[];
};

export const EXPLANATION_TEXTS: ExplanationText[] = [
  {
    id: "photosynthesis",
    title: "Photosynthesis",
    content:
      "Photosynthesis is the process by which green plants, algae, and some bacteria convert light energy, usually from the sun, into chemical energy stored in glucose. This process occurs mainly in the leaves of plants, specifically in the chloroplasts, which contain a green pigment called chlorophyll. During photosynthesis, plants absorb carbon dioxide from the air through tiny pores called stomata and water from the soil through their roots. Using sunlight, they transform these raw materials into glucose and oxygen. The oxygen is released into the atmosphere as a byproduct, making photosynthesis essential for life on Earth.",
    questions: [
      {
        id: "p1",
        text: "Photosynthesis is the process by which green plants, algae, and some bacteria convert light energy into chemical energy stored in glucose.",
        question: "Where does photosynthesis mainly occur in plants?",
        options: ["In the roots", "In the flowers", "In the chloroplasts of leaves", "In the stem"],
        correct: 2,
        explanation: "Photosynthesis occurs mainly in the chloroplasts of leaves, which contain chlorophyll.",
        difficulty: "easy",
      },
      {
        id: "p2",
        text: "Photosynthesis is the process by which green plants convert light energy into chemical energy.",
        question: "What green pigment in chloroplasts absorbs sunlight for photosynthesis?",
        options: ["Carotene", "Chlorophyll", "Anthocyanin", "Melanin"],
        correct: 1,
        explanation: "Chlorophyll is the green pigment found in chloroplasts that absorbs sunlight.",
        difficulty: "easy",
      },
      {
        id: "p3",
        text: "During photosynthesis, plants absorb carbon dioxide and water to produce glucose and oxygen.",
        question: "What byproduct of photosynthesis is released into the atmosphere?",
        options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"],
        correct: 2,
        explanation: "Oxygen is released as a byproduct during photosynthesis.",
        difficulty: "easy",
      },
      {
        id: "p4",
        text: "Plants absorb carbon dioxide from the air through tiny pores called stomata.",
        question: "Through which structure do plants absorb carbon dioxide?",
        options: ["Roots", "Stomata", "Xylem", "Phloem"],
        correct: 1,
        explanation: "Plants absorb carbon dioxide through tiny pores called stomata.",
        difficulty: "medium",
      },
      {
        id: "p5",
        text: "Photosynthesis converts light energy into chemical energy stored as glucose.",
        question: "Why is photosynthesis essential for life on Earth?",
        options: [
          "It produces nitrogen for the atmosphere",
          "It releases oxygen and provides food energy",
          "It removes excess water from the environment",
          "It creates soil nutrients for plants",
        ],
        correct: 1,
        explanation: "Photosynthesis releases oxygen and converts light into glucose, supporting life on Earth.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "water_cycle",
    title: "The Water Cycle",
    content:
      "The water cycle, also known as the hydrological cycle, describes the continuous movement of water on, above, and below the surface of the Earth. Water evaporates from oceans, lakes, and rivers when heated by the sun, turning into water vapor. This vapor rises into the atmosphere, cools, and condenses to form clouds through a process called condensation. When clouds become heavy enough, water falls back to Earth as precipitation in the form of rain, snow, or hail. This water flows into rivers, lakes, and oceans, or seeps into the ground as groundwater, eventually evaporating again to continue the cycle.",
    questions: [
      {
        id: "wc1",
        text: "The water cycle describes the continuous movement of water on, above, and below Earth's surface.",
        question: "What process turns liquid water into water vapor?",
        options: ["Condensation", "Precipitation", "Evaporation", "Transpiration"],
        correct: 2,
        explanation: "Evaporation turns liquid water into water vapor when heated by the sun.",
        difficulty: "easy",
      },
      {
        id: "wc2",
        text: "Water vapor rises and cools to form clouds through condensation.",
        question: "What is the process called when water vapor cools and forms clouds?",
        options: ["Evaporation", "Condensation", "Precipitation", "Infiltration"],
        correct: 1,
        explanation: "Condensation is when water vapor cools and transforms into liquid water droplets, forming clouds.",
        difficulty: "easy",
      },
      {
        id: "wc3",
        text: "Water falls back to Earth as precipitation in the form of rain, snow, or hail.",
        question: "Which of the following is NOT a form of precipitation?",
        options: ["Rain", "Snow", "Hail", "Fog"],
        correct: 3,
        explanation: "Fog is water vapor condensed near the ground, not precipitation falling from clouds.",
        difficulty: "medium",
      },
      {
        id: "wc4",
        text: "Water flows into rivers, lakes, and oceans, or seeps into the ground as groundwater.",
        question: "What happens to water that seeps into the ground?",
        options: ["It immediately evaporates", "It becomes groundwater", "It turns into ice", "It creates rivers"],
        correct: 1,
        explanation: "Water that seeps into the ground becomes groundwater, stored in underground reservoirs.",
        difficulty: "medium",
      },
      {
        id: "wc5",
        text: "The water cycle is a continuous process driven by solar energy.",
        question: "What is the primary energy source that drives the water cycle?",
        options: ["Wind energy", "Geothermal energy", "Solar energy", "Nuclear energy"],
        correct: 2,
        explanation: "The sun (solar energy) drives the water cycle by providing heat for evaporation.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "volcanoes",
    title: "Volcanoes",
    content:
      "A volcano is an opening in Earth's crust through which molten rock, gas, and ash can escape. Volcanoes form when magma from deep within the Earth pushes up through cracks in the crust. When magma reaches the surface, it is called lava. Volcanic eruptions can be explosive or gentle, depending on the composition of the magma. Explosive eruptions occur when magma contains large amounts of dissolved gases. Volcanoes can be found along tectonic plate boundaries or over hotspots in the mantle. Famous volcanoes include Mount Vesuvius, Krakatau, and Mauna Loa. Despite their destructive power, volcanic soils are extremely fertile for agriculture.",
    questions: [
      {
        id: "v1",
        text: "A volcano is an opening in Earth's crust through which molten rock, gas, and ash escape.",
        question: "What is magma called when it reaches Earth's surface?",
        options: ["Ash", "Lava", "Pumice", "Obsidian"],
        correct: 1,
        explanation: "When magma reaches Earth's surface through a volcano, it is called lava.",
        difficulty: "easy",
      },
      {
        id: "v2",
        text: "Volcanic eruptions can be explosive or gentle depending on magma composition.",
        question: "What causes explosive volcanic eruptions?",
        options: [
          "Cool temperatures",
          "Large amounts of dissolved gases in magma",
          "Thin magma with low viscosity",
          "Presence of water near the volcano",
        ],
        correct: 1,
        explanation: "Explosive eruptions occur when magma contains large amounts of dissolved gases.",
        difficulty: "medium",
      },
      {
        id: "v3",
        text: "Volcanoes form along tectonic plate boundaries or over mantle hotspots.",
        question: "Where are volcanoes commonly found?",
        options: [
          "Only in polar regions",
          "Only in the middle of continents",
          "Along tectonic plate boundaries or over hotspots",
          "Only underwater",
        ],
        correct: 2,
        explanation: "Volcanoes are found along tectonic plate boundaries or over hotspots in the mantle.",
        difficulty: "medium",
      },
      {
        id: "v4",
        text: "Despite their destructive power, volcanic soils are extremely fertile.",
        question: "Why are volcanic soils considered beneficial for agriculture?",
        options: [
          "They retain too much water",
          "They are extremely fertile",
          "They prevent plant diseases",
          "They have no nutrients",
        ],
        correct: 1,
        explanation: "Volcanic soils are extremely fertile, making them excellent for agriculture.",
        difficulty: "easy",
      },
      {
        id: "v5",
        text: "Magma pushes up through cracks in Earth's crust to form volcanoes.",
        question: "What is the term for molten rock beneath Earth's surface?",
        options: ["Lava", "Magma", "Ash", "Pumice"],
        correct: 1,
        explanation: "Magma is the term for molten rock beneath Earth's surface; it becomes lava when it erupts.",
        difficulty: "easy",
      },
    ],
  },
  {
    id: "greenhouse",
    title: "The Greenhouse Effect",
    content:
      "The greenhouse effect is a natural process that warms Earth's surface. When the sun's energy reaches Earth, some is absorbed by the surface and some is reflected back toward space. Greenhouse gases in the atmosphere, including carbon dioxide, methane, and water vapor, trap some of this reflected energy, preventing it from escaping into space. This keeps Earth warm enough to support life. However, human activities such as burning fossil fuels, deforestation, and industrial processes have increased the concentration of greenhouse gases, enhancing the greenhouse effect and causing global warming. This leads to climate change, rising sea levels, and extreme weather events.",
    questions: [
      {
        id: "g1",
        text: "The greenhouse effect is a natural process that warms Earth's surface.",
        question: "Which gases are considered greenhouse gases?",
        options: [
          "Oxygen and nitrogen",
          "Carbon dioxide, methane, and water vapor",
          "Hydrogen and helium",
          "Argon and neon",
        ],
        correct: 1,
        explanation: "Carbon dioxide, methane, and water vapor are the main greenhouse gases.",
        difficulty: "easy",
      },
      {
        id: "g2",
        text: "Greenhouse gases trap reflected energy and prevent it from escaping into space.",
        question: "What is the primary role of greenhouse gases in Earth's atmosphere?",
        options: [
          "To block incoming sunlight",
          "To trap heat and keep Earth warm",
          "To reflect all sunlight back to space",
          "To produce oxygen for breathing",
        ],
        correct: 1,
        explanation: "Greenhouse gases trap heat (reflected energy) and keep Earth at a temperature that supports life.",
        difficulty: "easy",
      },
      {
        id: "g3",
        text: "Human activities have increased greenhouse gas concentrations, enhancing the greenhouse effect.",
        question: "Which human activity contributes MOST to increasing greenhouse gases?",
        options: ["Swimming", "Burning fossil fuels", "Growing food", "Reading books"],
        correct: 1,
        explanation: "Burning fossil fuels releases large amounts of carbon dioxide, a major greenhouse gas.",
        difficulty: "medium",
      },
      {
        id: "g4",
        text: "Enhanced greenhouse effect leads to global warming, rising sea levels, and extreme weather.",
        question: "What is one consequence of the enhanced greenhouse effect?",
        options: [
          "Colder global temperatures",
          "Decreased sea levels",
          "Rising sea levels",
          "More rainfall in deserts only",
        ],
        correct: 2,
        explanation: "The enhanced greenhouse effect causes global warming, which leads to rising sea levels.",
        difficulty: "medium",
      },
      {
        id: "g5",
        text: "The greenhouse effect is necessary for life but becomes dangerous when enhanced by human activity.",
        question: "Without any greenhouse effect, what would happen to Earth?",
        options: [
          "Earth would be too hot for life",
          "Earth would be too cold for life",
          "Earth would have perfect temperatures",
          "Nothing would change",
        ],
        correct: 1,
        explanation: "Without the greenhouse effect, Earth would be too cold (about -18°C) to support life.",
        difficulty: "hard",
      },
    ],
  },
  {
    id: "digestive",
    title: "The Human Digestive System",
    content:
      "The human digestive system is responsible for breaking down food into nutrients that the body can absorb and use for energy, growth, and repair. Digestion begins in the mouth, where teeth chew food and saliva begins breaking down carbohydrates. The food travels down the esophagus to the stomach, where acid and enzymes break it down further. The partially digested food, called chyme, then moves into the small intestine, where most nutrients are absorbed into the bloodstream. The remaining material passes into the large intestine, where water is absorbed, and the solid waste is eventually expelled through the rectum and anus.",
    questions: [
      {
        id: "d1",
        text: "The digestive system breaks down food into nutrients the body can absorb.",
        question: "Where does digestion begin?",
        options: ["In the stomach", "In the small intestine", "In the mouth", "In the esophagus"],
        correct: 2,
        explanation: "Digestion begins in the mouth, where teeth chew food and saliva breaks down carbohydrates.",
        difficulty: "easy",
      },
      {
        id: "d2",
        text: "Saliva in the mouth begins breaking down carbohydrates during digestion.",
        question: "What does saliva primarily help to digest?",
        options: ["Proteins", "Fats", "Carbohydrates", "Vitamins"],
        correct: 2,
        explanation: "Saliva contains enzymes that begin breaking down carbohydrates in the mouth.",
        difficulty: "medium",
      },
      {
        id: "d3",
        text: "The stomach uses acid and enzymes to break down food further.",
        question: "What is the partially digested food in the stomach called?",
        options: ["Bolus", "Chyme", "Mucus", "Bile"],
        correct: 1,
        explanation: "The partially digested food in the stomach is called chyme.",
        difficulty: "medium",
      },
      {
        id: "d4",
        text: "Most nutrients are absorbed into the bloodstream in the small intestine.",
        question: "Where does most nutrient absorption occur?",
        options: ["In the mouth", "In the stomach", "In the small intestine", "In the large intestine"],
        correct: 2,
        explanation: "Most nutrients are absorbed into the bloodstream through the walls of the small intestine.",
        difficulty: "easy",
      },
      {
        id: "d5",
        text: "The large intestine absorbs water from remaining material before waste is expelled.",
        question: "What is the main function of the large intestine?",
        options: [
          "Breaking down proteins",
          "Absorbing water from remaining material",
          "Producing digestive enzymes",
          "Storing bile",
        ],
        correct: 1,
        explanation: "The large intestine mainly absorbs water from the remaining undigested material.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "earthquakes",
    title: "Earthquakes",
    content:
      "An earthquake is the shaking of Earth's surface caused by the sudden release of energy stored in Earth's lithosphere. This energy release creates seismic waves that travel through the Earth. Most earthquakes occur along fault lines, which are fractures in Earth's crust where tectonic plates meet and interact. When the stress built up between plates is suddenly released, it sends out waves of energy in all directions. The point within Earth where the earthquake originates is called the focus (or hypocenter), while the point on the surface directly above it is the epicenter. Earthquakes are measured using the Richter scale or the moment magnitude scale.",
    questions: [
      {
        id: "e1",
        text: "Earthquakes are caused by the sudden release of energy in Earth's lithosphere.",
        question: "What are the waves of energy released by an earthquake called?",
        options: ["Sound waves", "Light waves", "Seismic waves", "Electromagnetic waves"],
        correct: 2,
        explanation: "Earthquakes create seismic waves that travel through the Earth.",
        difficulty: "easy",
      },
      {
        id: "e2",
        text: "Most earthquakes occur along fault lines where tectonic plates meet.",
        question: "What is a fault line?",
        options: [
          "A type of mountain",
          "A fracture in Earth's crust where plates interact",
          "A deep ocean trench",
          "A volcanic opening",
        ],
        correct: 1,
        explanation: "A fault line is a fracture in Earth's crust where tectonic plates meet and interact.",
        difficulty: "easy",
      },
      {
        id: "e3",
        text: "The focus is where the earthquake originates within Earth; the epicenter is directly above on the surface.",
        question: "What is the epicenter of an earthquake?",
        options: [
          "The point inside Earth where the earthquake starts",
          "The point on the surface directly above the focus",
          "The area of greatest destruction",
          "The center of a tectonic plate",
        ],
        correct: 1,
        explanation: "The epicenter is the point on Earth's surface directly above the earthquake's focus.",
        difficulty: "medium",
      },
      {
        id: "e4",
        text: "Earthquakes are measured using the Richter scale or moment magnitude scale.",
        question: "Which scale is used to measure the magnitude of earthquakes?",
        options: ["Beaufort scale", "Richter scale", "Celsius scale", "Decibel scale"],
        correct: 1,
        explanation: "The Richter scale (or moment magnitude scale) measures earthquake magnitude.",
        difficulty: "easy",
      },
      {
        id: "e5",
        text: "Stress builds up between tectonic plates and is suddenly released, causing earthquakes.",
        question: "Why do earthquakes occur more frequently at plate boundaries?",
        options: [
          "Because there is more water there",
          "Because stress builds up where plates interact",
          "Because of volcanic activity only",
          "Because the crust is thicker there",
        ],
        correct: 1,
        explanation: "Stress builds up between interacting plates at boundaries and is suddenly released as an earthquake.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "solar_system",
    title: "The Solar System",
    content:
      "The solar system consists of the Sun and everything that orbits around it, including eight planets, their moons, dwarf planets, asteroids, comets, and interplanetary dust. The Sun, a star, contains about 99.86% of the total mass of the solar system. The eight planets, in order from the Sun, are Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune. The first four are called terrestrial planets because they have rocky surfaces, while the outer four are gas giants. Jupiter is the largest planet in the solar system. The asteroid belt lies between Mars and Jupiter, and beyond Neptune lies the Kuiper Belt.",
    questions: [
      {
        id: "ss1",
        text: "The solar system consists of the Sun and everything that orbits it, including eight planets.",
        question: "How many planets are in our solar system?",
        options: ["Seven", "Eight", "Nine", "Ten"],
        correct: 1,
        explanation: "Our solar system has eight planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.",
        difficulty: "easy",
      },
      {
        id: "ss2",
        text: "The first four planets are terrestrial (rocky) while the outer four are gas giants.",
        question: "Which of the following is a terrestrial (rocky) planet?",
        options: ["Jupiter", "Saturn", "Mars", "Neptune"],
        correct: 2,
        explanation: "Mars is a terrestrial planet with a rocky surface. Jupiter, Saturn, and Neptune are gas giants.",
        difficulty: "easy",
      },
      {
        id: "ss3",
        text: "The Sun contains about 99.86% of the total mass of the solar system.",
        question: "What is the largest object in the solar system?",
        options: ["Jupiter", "Saturn", "The Sun", "Earth"],
        correct: 2,
        explanation: "The Sun is by far the largest object, containing 99.86% of the solar system's mass.",
        difficulty: "easy",
      },
      {
        id: "ss4",
        text: "The asteroid belt lies between Mars and Jupiter.",
        question: "Where is the asteroid belt located?",
        options: [
          "Between Earth and Mars",
          "Between Mars and Jupiter",
          "Between Jupiter and Saturn",
          "Beyond Neptune",
        ],
        correct: 1,
        explanation: "The asteroid belt is located between Mars and Jupiter.",
        difficulty: "medium",
      },
      {
        id: "ss5",
        text: "Beyond Neptune lies the Kuiper Belt.",
        question: "What lies beyond Neptune in our solar system?",
        options: ["The asteroid belt", "Another galaxy", "The Kuiper Belt", "The Sun's corona"],
        correct: 2,
        explanation: "The Kuiper Belt lies beyond Neptune, containing dwarf planets and icy bodies.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "rainforests",
    title: "Rainforests",
    content:
      "Rainforests are dense forests characterized by high rainfall of at least 1,750–2,000 mm per year. They are found near the equator in regions of South America, Central Africa, Southeast Asia, and Australia. Rainforests cover only about 6% of Earth's surface but are home to more than half of the world's plant and animal species. They are often called the 'lungs of the Earth' because they absorb large amounts of carbon dioxide and produce oxygen through photosynthesis. The Amazon Rainforest in South America is the world's largest tropical rainforest. Deforestation threatens these vital ecosystems, leading to biodiversity loss and climate change.",
    questions: [
      {
        id: "r1",
        text: "Rainforests are dense forests with high annual rainfall found near the equator.",
        question: "What minimum annual rainfall characterizes a rainforest?",
        options: ["500 mm", "1,000 mm", "1,750-2,000 mm", "3,000 mm"],
        correct: 2,
        explanation: "Rainforests receive at least 1,750–2,000 mm of rain per year.",
        difficulty: "medium",
      },
      {
        id: "r2",
        text: "Rainforests cover 6% of Earth's surface but house more than half of all species.",
        question: "What percentage of Earth's species live in rainforests?",
        options: ["Less than 10%", "About 25%", "More than half", "Almost all"],
        correct: 2,
        explanation: "Although covering only 6% of Earth's surface, rainforests are home to more than half of all species.",
        difficulty: "medium",
      },
      {
        id: "r3",
        text: "Rainforests are called the 'lungs of the Earth' because they absorb CO2 and produce oxygen.",
        question: "Why are rainforests called the 'lungs of the Earth'?",
        options: [
          "They breathe like animals",
          "They absorb CO2 and produce oxygen through photosynthesis",
          "They store water underground",
          "They regulate wind patterns",
        ],
        correct: 1,
        explanation: "Rainforests absorb CO2 and produce oxygen, much like lungs exchange gases in our body.",
        difficulty: "easy",
      },
      {
        id: "r4",
        text: "The Amazon Rainforest is the world's largest tropical rainforest.",
        question: "Where is the world's largest tropical rainforest located?",
        options: ["Central Africa", "Southeast Asia", "Australia", "South America"],
        correct: 3,
        explanation: "The Amazon Rainforest in South America is the world's largest tropical rainforest.",
        difficulty: "easy",
      },
      {
        id: "r5",
        text: "Deforestation threatens rainforests, causing biodiversity loss and climate change.",
        question: "What is the main threat to rainforests today?",
        options: ["Earthquakes", "Deforestation", "Volcanic eruptions", "Flooding"],
        correct: 1,
        explanation: "Deforestation (clearing trees) is the main threat to rainforests worldwide.",
        difficulty: "easy",
      },
    ],
  },
  {
    id: "lightning",
    title: "Lightning and Thunder",
    content:
      "Lightning is a powerful electrical discharge that occurs during thunderstorms. It is caused by the buildup of static electricity within storm clouds. As ice crystals and water droplets collide inside a cumulonimbus cloud, positive charges accumulate at the top and negative charges at the bottom. When the electrical potential difference between the cloud and the ground becomes large enough, a massive discharge of electricity occurs — this is lightning. Thunder is the sound produced by the rapid expansion of heated air around a lightning bolt. Since light travels faster than sound, we see lightning before we hear thunder. You can estimate the distance of a storm by counting seconds between lightning and thunder.",
    questions: [
      {
        id: "l1",
        text: "Lightning is a powerful electrical discharge caused by static electricity buildup in storm clouds.",
        question: "What type of cloud produces lightning and thunder?",
        options: ["Cirrus", "Stratus", "Cumulus", "Cumulonimbus"],
        correct: 3,
        explanation: "Cumulonimbus clouds are the tall storm clouds that produce lightning and thunder.",
        difficulty: "medium",
      },
      {
        id: "l2",
        text: "Positive charges accumulate at the top and negative charges at the bottom of storm clouds.",
        question: "Where do negative charges accumulate in a thunderstorm cloud?",
        options: ["At the top", "In the middle", "At the bottom", "Outside the cloud"],
        correct: 2,
        explanation: "Negative charges accumulate at the bottom of storm clouds during a thunderstorm.",
        difficulty: "medium",
      },
      {
        id: "l3",
        text: "Thunder is the sound produced by the rapid expansion of heated air around a lightning bolt.",
        question: "What causes thunder?",
        options: [
          "Clouds colliding together",
          "Rapid expansion of heated air around lightning",
          "Rain hitting the ground",
          "Wind blowing through mountains",
        ],
        correct: 1,
        explanation: "Thunder is caused by the rapid expansion of air heated by the lightning bolt.",
        difficulty: "easy",
      },
      {
        id: "l4",
        text: "We see lightning before we hear thunder because light travels faster than sound.",
        question: "Why do we see lightning before hearing thunder?",
        options: [
          "Lightning is closer to us",
          "Thunder travels underground",
          "Light travels faster than sound",
          "Our eyes react faster than our ears",
        ],
        correct: 2,
        explanation: "Light travels at 300,000 km/s while sound travels at 340 m/s, so we see lightning first.",
        difficulty: "easy",
      },
      {
        id: "l5",
        text: "You can estimate storm distance by counting seconds between lightning and thunder.",
        question: "How can you estimate the distance of a thunderstorm?",
        options: [
          "By measuring rainfall",
          "By counting seconds between lightning and thunder",
          "By checking wind speed",
          "By looking at cloud color",
        ],
        correct: 1,
        explanation: "Counting seconds between lightning and thunder (and dividing by 3) gives approximate distance in km.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "tides",
    title: "Ocean Tides",
    content:
      "Tides are the regular rise and fall of ocean water levels, primarily caused by the gravitational pull of the Moon and, to a lesser extent, the Sun. The Moon's gravity pulls ocean water toward it, creating a bulge of water on the side of Earth facing the Moon. Another bulge forms on the opposite side due to inertial forces. As Earth rotates, different areas pass through these bulges, experiencing high tide, then low tide. When the Sun, Moon, and Earth are aligned, their combined gravitational effects create especially high and low tides called spring tides. When the Sun and Moon are at right angles to Earth, the gravitational forces partially cancel, creating neap tides.",
    questions: [
      {
        id: "t1",
        text: "Tides are caused by the gravitational pull of the Moon and Sun on ocean water.",
        question: "What is the PRIMARY cause of ocean tides?",
        options: ["Wind patterns", "Earth's rotation", "Moon's gravitational pull", "Sun's heat"],
        correct: 2,
        explanation: "The Moon's gravitational pull is the primary cause of ocean tides.",
        difficulty: "easy",
      },
      {
        id: "t2",
        text: "The Moon's gravity creates a water bulge on the side facing the Moon and another on the opposite side.",
        question: "How many tidal bulges exist on Earth at the same time?",
        options: ["One", "Two", "Three", "Four"],
        correct: 1,
        explanation: "There are two tidal bulges — one facing the Moon and one on the opposite side of Earth.",
        difficulty: "medium",
      },
      {
        id: "t3",
        text: "Spring tides occur when the Sun, Moon, and Earth are aligned.",
        question: "When do spring tides occur?",
        options: [
          "Every spring season",
          "When Sun, Moon, and Earth are aligned",
          "When Sun and Moon are at right angles",
          "Only during storms",
        ],
        correct: 1,
        explanation: "Spring tides occur when the Sun, Moon, and Earth are aligned, combining gravitational forces.",
        difficulty: "medium",
      },
      {
        id: "t4",
        text: "Neap tides form when the Sun and Moon are at right angles to Earth.",
        question: "What causes neap tides?",
        options: [
          "When Sun, Moon, and Earth are aligned",
          "When Sun and Moon are at right angles to Earth",
          "During full moon only",
          "During earthquakes",
        ],
        correct: 1,
        explanation: "Neap tides form when the Sun and Moon are at right angles, partially canceling each other's pull.",
        difficulty: "hard",
      },
      {
        id: "t5",
        text: "As Earth rotates, different areas experience high and low tides.",
        question: "Why do different areas of Earth experience high and low tides at different times?",
        options: [
          "Because oceans have different depths",
          "Because Earth rotates through tidal bulges",
          "Because the Moon moves very fast",
          "Because continents block tidal waves",
        ],
        correct: 1,
        explanation: "As Earth rotates, different coastal areas pass through the tidal bulges, experiencing high then low tide.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "migration",
    title: "Bird Migration",
    content:
      "Migration is the seasonal movement of animals from one region to another, typically in response to changes in food availability, temperature, or daylight hours. Birds are the most well-known migratory animals. They travel between breeding grounds in summer and warmer wintering areas in winter. Birds navigate using various cues including the position of the sun and stars, Earth's magnetic field, landmarks, and even smell. Some birds, like the Arctic Tern, migrate from the Arctic to the Antarctic and back — a round trip of about 70,000 kilometers. Migration is an energy-intensive process; birds build up fat reserves before migrating to fuel their journeys.",
    questions: [
      {
        id: "m1",
        text: "Migration is the seasonal movement of animals in response to changes in food, temperature, or daylight.",
        question: "What is one main reason birds migrate?",
        options: [
          "To escape predators permanently",
          "In response to changes in food availability and temperature",
          "To find new nesting materials",
          "Because they enjoy traveling",
        ],
        correct: 1,
        explanation: "Birds migrate mainly due to changes in food availability and temperature through the seasons.",
        difficulty: "easy",
      },
      {
        id: "m2",
        text: "Birds navigate using the sun, stars, Earth's magnetic field, and landmarks.",
        question: "How do birds navigate during migration?",
        options: [
          "They follow roads and highways",
          "They use sun, stars, magnetic field, and landmarks",
          "They only follow other birds",
          "They use GPS technology",
        ],
        correct: 1,
        explanation: "Birds use multiple navigation tools: sun position, stars, Earth's magnetic field, and landmarks.",
        difficulty: "medium",
      },
      {
        id: "m3",
        text: "The Arctic Tern migrates about 70,000 km round trip from Arctic to Antarctic.",
        question: "Which bird is known for the longest migration journey?",
        options: ["Eagle", "Penguin", "Arctic Tern", "Sparrow"],
        correct: 2,
        explanation: "The Arctic Tern makes the longest migration of about 70,000 km round trip.",
        difficulty: "medium",
      },
      {
        id: "m4",
        text: "Birds build up fat reserves before migrating to fuel their long journeys.",
        question: "How do birds prepare their bodies for migration?",
        options: [
          "They drink extra water",
          "They shed their feathers",
          "They build up fat reserves",
          "They sleep extra hours",
        ],
        correct: 2,
        explanation: "Birds build up fat reserves before migration to use as energy fuel during the journey.",
        difficulty: "medium",
      },
      {
        id: "m5",
        text: "Birds travel between breeding grounds in summer and warmer wintering areas in winter.",
        question: "To what kind of area do birds typically migrate in winter?",
        options: [
          "Colder polar regions",
          "Higher altitude mountains",
          "Warmer wintering areas",
          "Deeper ocean shores",
        ],
        correct: 2,
        explanation: "Birds migrate to warmer areas in winter where food is more readily available.",
        difficulty: "easy",
      },
    ],
  },
  {
    id: "tornadoes",
    title: "Tornadoes",
    content:
      "A tornado is a violently rotating column of air that extends from a thunderstorm cloud to the ground. Tornadoes form when warm, moist air collides with cool, dry air, creating atmospheric instability. Wind shear — the change in wind speed and direction at different altitudes — causes the air to begin rotating. This rotating air can be sucked into a thunderstorm and tilted vertically to form a tornado funnel. The Fujita scale (or Enhanced Fujita scale) rates tornadoes from F0 to F5 based on wind speeds and damage. The central United States, known as Tornado Alley, experiences the most tornadoes in the world due to the frequent meeting of warm Gulf air and cold Arctic air.",
    questions: [
      {
        id: "tor1",
        text: "A tornado is a violently rotating column of air extending from a thunderstorm to the ground.",
        question: "What is a tornado?",
        options: [
          "A type of hurricane",
          "A rotating column of water",
          "A violently rotating column of air from thunderstorm to ground",
          "A type of blizzard",
        ],
        correct: 2,
        explanation: "A tornado is a violently rotating column of air extending from a thunderstorm to the ground.",
        difficulty: "easy",
      },
      {
        id: "tor2",
        text: "Tornadoes form when warm moist air collides with cool dry air creating atmospheric instability.",
        question: "What atmospheric condition leads to tornado formation?",
        options: [
          "Cold moist air meeting warm dry air",
          "Warm moist air meeting cool dry air",
          "Two cold air masses colliding",
          "High pressure meeting low pressure in winter",
        ],
        correct: 1,
        explanation: "Tornadoes form when warm, moist air collides with cool, dry air, creating instability.",
        difficulty: "medium",
      },
      {
        id: "tor3",
        text: "Wind shear causes air to begin rotating and can form a tornado funnel.",
        question: "What is wind shear?",
        options: [
          "Strong downward winds",
          "Change in wind speed and direction at different altitudes",
          "Horizontal winds above 200 km/h",
          "Circular ocean currents",
        ],
        correct: 1,
        explanation: "Wind shear is the change in wind speed and direction at different altitudes, enabling tornado rotation.",
        difficulty: "hard",
      },
      {
        id: "tor4",
        text: "Tornadoes are rated F0 to F5 on the Fujita scale based on wind speeds and damage.",
        question: "What scale rates tornado intensity?",
        options: ["Richter scale", "Beaufort scale", "Fujita scale", "Celsius scale"],
        correct: 2,
        explanation: "The Fujita (or Enhanced Fujita) scale rates tornadoes F0–F5 based on wind speed and damage.",
        difficulty: "medium",
      },
      {
        id: "tor5",
        text: "Tornado Alley in the central United States experiences the most tornadoes due to air mass collisions.",
        question: "Why does 'Tornado Alley' experience so many tornadoes?",
        options: [
          "It is near the ocean",
          "Warm Gulf air frequently meets cold Arctic air there",
          "It has many mountains that create wind",
          "It gets the most rainfall in the world",
        ],
        correct: 1,
        explanation: "Tornado Alley experiences frequent collisions of warm Gulf air and cold Arctic air, ideal for tornadoes.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "coral_reefs",
    title: "Coral Reefs",
    content:
      "Coral reefs are underwater ecosystems built by colonies of tiny animals called coral polyps, which secrete calcium carbonate to form hard skeletons. These skeletons accumulate over thousands of years to form the reef structure. Coral reefs are often called the 'rainforests of the sea' because they support an extraordinary diversity of marine life — about 25% of all marine species. Reef-building corals require warm, clear, shallow, and clean water. The Great Barrier Reef off the coast of Australia is the world's largest coral reef system. Coral reefs face severe threats from rising ocean temperatures, ocean acidification, overfishing, and pollution, leading to coral bleaching.",
    questions: [
      {
        id: "cr1",
        text: "Coral reefs are built by coral polyps that secrete calcium carbonate to form hard skeletons.",
        question: "What do coral polyps secrete to build the reef structure?",
        options: ["Salt", "Calcium carbonate", "Silica", "Iron oxide"],
        correct: 1,
        explanation: "Coral polyps secrete calcium carbonate, which accumulates to form the reef's hard skeleton.",
        difficulty: "medium",
      },
      {
        id: "cr2",
        text: "Coral reefs are called the 'rainforests of the sea' because they support 25% of all marine species.",
        question: "What percentage of all marine species do coral reefs support?",
        options: ["5%", "10%", "25%", "50%"],
        correct: 2,
        explanation: "Coral reefs support about 25% of all marine species despite covering less than 1% of the ocean floor.",
        difficulty: "medium",
      },
      {
        id: "cr3",
        text: "Reef-building corals need warm, clear, shallow, and clean water.",
        question: "What conditions do reef-building corals require to thrive?",
        options: [
          "Cold, deep, murky water",
          "Warm, clear, shallow, clean water",
          "Freshwater rivers",
          "Extremely cold polar water",
        ],
        correct: 1,
        explanation: "Reef-building corals require warm, clear, shallow, and clean saltwater to survive.",
        difficulty: "easy",
      },
      {
        id: "cr4",
        text: "The Great Barrier Reef is the world's largest coral reef system.",
        question: "Where is the Great Barrier Reef located?",
        options: ["Near Brazil", "Near Indonesia", "Off the coast of Australia", "In the Caribbean Sea"],
        correct: 2,
        explanation: "The Great Barrier Reef is located off the northeastern coast of Australia.",
        difficulty: "easy",
      },
      {
        id: "cr5",
        text: "Coral bleaching is caused by rising temperatures, acidification, overfishing, and pollution.",
        question: "What is coral bleaching caused by?",
        options: [
          "Too much sunlight reaching deep water",
          "Rising ocean temperatures and acidification",
          "Excessive reef fishing",
          "Natural aging of coral",
        ],
        correct: 1,
        explanation: "Coral bleaching is primarily caused by rising ocean temperatures that stress the coral, causing them to expel algae.",
        difficulty: "hard",
      },
    ],
  },
  {
    id: "moon",
    title: "The Moon",
    content:
      "The Moon is Earth's only natural satellite and the fifth-largest moon in the solar system. It orbits Earth at an average distance of about 384,400 km, completing one orbit every 27.3 days — called the sidereal period. The Moon's gravitational pull on Earth causes ocean tides and stabilizes Earth's axial tilt. The Moon has no atmosphere, so it experiences extreme temperature variations and has no weather. Its surface is covered with craters, mountains, and large flat plains called maria, formed by ancient volcanic activity. The Moon always shows the same face to Earth due to synchronous rotation. Humans first walked on the Moon in 1969 during NASA's Apollo 11 mission.",
    questions: [
      {
        id: "mo1",
        text: "The Moon is Earth's only natural satellite, orbiting at about 384,400 km.",
        question: "How long does the Moon take to complete one orbit around Earth?",
        options: ["7 days", "14 days", "27.3 days", "30 days"],
        correct: 2,
        explanation: "The Moon completes one orbit around Earth in about 27.3 days (the sidereal period).",
        difficulty: "medium",
      },
      {
        id: "mo2",
        text: "The Moon's gravity causes ocean tides and stabilizes Earth's axial tilt.",
        question: "Besides causing tides, what does the Moon's gravity do for Earth?",
        options: [
          "It creates Earth's magnetic field",
          "It stabilizes Earth's axial tilt",
          "It generates Earth's heat",
          "It controls Earth's rotation speed",
        ],
        correct: 1,
        explanation: "The Moon's gravity stabilizes Earth's axial tilt, helping maintain stable seasons.",
        difficulty: "hard",
      },
      {
        id: "mo3",
        text: "The Moon has no atmosphere, so it experiences extreme temperatures and no weather.",
        question: "Why does the Moon have no weather?",
        options: [
          "It is too close to Earth",
          "It has no atmosphere",
          "It is too cold",
          "It has no water",
        ],
        correct: 1,
        explanation: "Without an atmosphere, the Moon has no weather, wind, rain, or temperature moderation.",
        difficulty: "easy",
      },
      {
        id: "mo4",
        text: "The Moon always shows the same face to Earth due to synchronous rotation.",
        question: "Why do we always see the same side of the Moon from Earth?",
        options: [
          "The Moon does not rotate",
          "Because of synchronous rotation matching its orbital period",
          "The dark side is always facing away",
          "Because Earth's shadow covers the other side",
        ],
        correct: 1,
        explanation: "The Moon's rotation period equals its orbital period (synchronous rotation), so we always see the same face.",
        difficulty: "hard",
      },
      {
        id: "mo5",
        text: "Humans first walked on the Moon in 1969 during Apollo 11.",
        question: "When did humans first walk on the Moon?",
        options: ["1959", "1965", "1969", "1972"],
        correct: 2,
        explanation: "Astronauts Neil Armstrong and Buzz Aldrin first walked on the Moon in 1969 (Apollo 11).",
        difficulty: "easy",
      },
    ],
  },
  {
    id: "sound_waves",
    title: "Sound Waves",
    content:
      "Sound is a type of mechanical wave that travels through a medium such as air, water, or solids, by creating alternating regions of compression and rarefaction (expansion) in the medium. Sound cannot travel through a vacuum because there are no particles to vibrate and transmit the wave. The speed of sound depends on the medium it travels through — it moves faster through denser materials. In air at room temperature, sound travels at about 343 meters per second. The pitch of a sound is determined by its frequency (number of vibrations per second, measured in Hertz), while the loudness is determined by its amplitude. Ultrasound (above 20,000 Hz) is used in medical imaging and sonar.",
    questions: [
      {
        id: "sw1",
        text: "Sound is a mechanical wave that travels through a medium by creating compressions and rarefactions.",
        question: "Through which of these can sound NOT travel?",
        options: ["Air", "Water", "Steel", "A vacuum"],
        correct: 3,
        explanation: "Sound cannot travel through a vacuum because there are no particles to vibrate and transmit waves.",
        difficulty: "easy",
      },
      {
        id: "sw2",
        text: "Sound moves faster through denser materials.",
        question: "In which medium does sound travel fastest?",
        options: ["Air", "Water", "Steel", "A vacuum"],
        correct: 2,
        explanation: "Sound travels fastest through dense solids like steel, where particles are closely packed.",
        difficulty: "medium",
      },
      {
        id: "sw3",
        text: "The pitch of sound is determined by its frequency, measured in Hertz.",
        question: "What determines the PITCH of a sound?",
        options: ["Amplitude", "Frequency (Hz)", "Speed", "Wavelength in cm"],
        correct: 1,
        explanation: "Pitch is determined by frequency — higher frequency means higher pitch.",
        difficulty: "medium",
      },
      {
        id: "sw4",
        text: "Loudness of sound is determined by its amplitude.",
        question: "What property of a sound wave determines its loudness?",
        options: ["Frequency", "Speed", "Amplitude", "Wavelength"],
        correct: 2,
        explanation: "Amplitude (the height of the wave) determines loudness — greater amplitude means louder sound.",
        difficulty: "medium",
      },
      {
        id: "sw5",
        text: "Ultrasound (above 20,000 Hz) is used in medical imaging and sonar.",
        question: "What is ultrasound used for?",
        options: [
          "Amplifying music",
          "Medical imaging and sonar",
          "Blocking noise pollution",
          "Measuring temperature",
        ],
        correct: 1,
        explanation: "Ultrasound (>20,000 Hz) is used in medical imaging (like pregnancy scans) and sonar technology.",
        difficulty: "easy",
      },
    ],
  },
];

export const LEVEL1_QUESTIONS = EXPLANATION_TEXTS;

export const LEVEL2_QUESTIONS: ExplanationText[] = [
  ...EXPLANATION_TEXTS.map((text) => ({
    ...text,
    questions: text.questions.map((q) => ({
      ...q,
      difficulty: q.difficulty === "easy" ? ("medium" as const) : q.difficulty === "medium" ? ("hard" as const) : ("hard" as const),
    })),
  })),
];

export function getRandomText(level: number, usedIds: string[]): ExplanationText {
  const pool = level === 1 ? LEVEL1_QUESTIONS : LEVEL2_QUESTIONS;
  const available = pool.filter((t) => !usedIds.includes(t.id));
  if (available.length === 0) return pool[Math.floor(Math.random() * pool.length)];
  return available[Math.floor(Math.random() * available.length)];
}

export const SNAKES_LEVEL1: Record<number, number> = {
  16: 6,
  47: 26,
  49: 11,
  56: 53,
  62: 19,
  64: 60,
  87: 24,
  93: 73,
  95: 75,
  99: 78,
};

export const LADDERS_LEVEL1: Record<number, number> = {
  4: 14,
  9: 31,
  20: 38,
  28: 84,
  40: 59,
  51: 67,
  63: 81,
  71: 91,
};

export const SNAKES_LEVEL2: Record<number, number> = {
  17: 7,
  24: 5,
  34: 16,
  46: 25,
  48: 10,
  55: 52,
  61: 18,
  64: 60,
  87: 24,
  92: 72,
  95: 75,
  99: 78,
  76: 43,
  82: 44,
};

export const LADDERS_LEVEL2: Record<number, { to: number; reward: { type: string; value: number; description: string } }> = {
  4: { to: 14, reward: { type: "points", value: 10, description: "+10 bonus points!" } },
  9: { to: 31, reward: { type: "bonus_roll", value: 1, description: "Bonus roll!" } },
  20: { to: 38, reward: { type: "points", value: 15, description: "+15 bonus points!" } },
  28: { to: 84, reward: { type: "bonus_roll", value: 1, description: "Extra roll!" } },
  36: { to: 57, reward: { type: "points", value: 20, description: "+20 bonus points!" } },
  40: { to: 59, reward: { type: "snake", value: -2, description: "Surprise snake! -2 squares!" } },
  51: { to: 67, reward: { type: "points", value: 25, description: "+25 bonus points!" } },
  63: { to: 81, reward: { type: "bonus_roll", value: 2, description: "2 bonus rolls!" } },
  71: { to: 91, reward: { type: "snake", value: -3, description: "Hidden trap! -3 squares!" } },
  77: { to: 98, reward: { type: "points", value: 30, description: "+30 bonus points!" } },
};
